using System;
using System.Collections.Generic;

namespace Zezoprice.Models
{
    public partial class Gcoordsystem
    {
        public string Csguid { get; set; } = null!;
        public int? Csguidtype { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public char? Basestoragetype { get; set; }
        public double? Stor2compmatrix1 { get; set; }
        public double? Stor2compmatrix2 { get; set; }
        public double? Stor2compmatrix3 { get; set; }
        public double? Stor2compmatrix4 { get; set; }
        public double? Stor2compmatrix5 { get; set; }
        public double? Stor2compmatrix6 { get; set; }
        public double? Stor2compmatrix7 { get; set; }
        public double? Stor2compmatrix8 { get; set; }
        public double? Stor2compmatrix9 { get; set; }
        public double? Stor2compmatrix10 { get; set; }
        public double? Stor2compmatrix11 { get; set; }
        public double? Stor2compmatrix12 { get; set; }
        public double? Stor2compmatrix13 { get; set; }
        public double? Stor2compmatrix14 { get; set; }
        public double? Stor2compmatrix15 { get; set; }
        public double? Stor2compmatrix16 { get; set; }
        public char? Heightstoragetype { get; set; }
        public char? Lonnormstorageopt { get; set; }
        public short? Geodeticdatum { get; set; }
        public short? Ellipsoid { get; set; }
        public double? Equatorialradius { get; set; }
        public double? Inverseflattening { get; set; }
        public short? Projalgorithm { get; set; }
        public double? Azimuthangle { get; set; }
        public double? Falsex { get; set; }
        public double? Falsey { get; set; }
        public char? Hemisphere { get; set; }
        public double? Latoforigin { get; set; }
        public double? Latoftruescale { get; set; }
        public double? Lonoforigin { get; set; }
        public double? Radofstandcircle { get; set; }
        public double? Scalereductfact { get; set; }
        public double? Standpar1 { get; set; }
        public double? Standpar2 { get; set; }
        public short? Zone { get; set; }
        public short? Pathnumber { get; set; }
        public short? Rownumber { get; set; }
        public short? Satellite { get; set; }
        public char? Xazdefopt { get; set; }
        public double? Geomheightoforig { get; set; }
        public double? Geomheightofpoint1 { get; set; }
        public double? Geomheightofpoint2 { get; set; }
        public double? Latofpoint1 { get; set; }
        public double? Latofpoint2 { get; set; }
        public double? Lonofpoint1 { get; set; }
        public double? Lonofpoint2 { get; set; }
        public double? Argumentofperigee { get; set; }
        public double? Earthrotperiod { get; set; }
        public char? Fourierexpansiondegree { get; set; }
        public char? Nodesinsimpsonintegration { get; set; }
        public double? Orbearthrotperiodratio { get; set; }
        public double? Orbecc { get; set; }
        public double? Orbinclination { get; set; }
        public double? Orboff { get; set; }
        public double? Orbperiod { get; set; }
        public double? Orbsemimajaxis { get; set; }
        public char? Oblmercdefmode { get; set; }
        public double? Latofmapcenter { get; set; }
        public char? Obllamconfcondefmode { get; set; }
        public double? Rotnorthpolelat { get; set; }
        public double? Rotnorthpolelon { get; set; }
        public double? Gaussianlat { get; set; }
        public double? Sphermodel { get; set; }
        public double? Spherradius { get; set; }
        public double? Latofbasispointa { get; set; }
        public double? Latofbasispointb { get; set; }
        public double? Latofbasispointc { get; set; }
        public double? Lonofbasispointa { get; set; }
        public double? Lonofbasispointb { get; set; }
        public double? Lonofbasispointc { get; set; }
        public char? Chamtriorigindefmode { get; set; }
        public char? Angorientationprojplanedefmode { get; set; }
        public double? Azofupwardtilt { get; set; }
        public double? Focallength { get; set; }
        public double? Heightaboveellipatnadir { get; set; }
        public double? Heightorigoflocalhorizsys { get; set; }
        public double? Latorigoflocalhorizsys { get; set; }
        public short? Locationofprojplanedefmode { get; set; }
        public double? Lonorigoflocalhorizsys { get; set; }
        public double? Perspcentergeocx { get; set; }
        public double? Perspcentergeocy { get; set; }
        public double? Perspcentergeocz { get; set; }
        public double? Perspcenterheight { get; set; }
        public double? Perspcenterlat { get; set; }
        public double? Perspcenterlon { get; set; }
        public double? Perspcenterxeast { get; set; }
        public double? Perspcenterynorth { get; set; }
        public double? Perspcenterzup { get; set; }
        public char? Refcoordsysdefmode { get; set; }
        public double? Rotaboutxaxis { get; set; }
        public double? Rotaboutyaxis { get; set; }
        public double? Rotaboutzaxis { get; set; }
        public double? Swingang { get; set; }
        public double? Tiltang { get; set; }
        public double? Extendprojmatrix1 { get; set; }
        public double? Extendprojmatrix2 { get; set; }
        public double? Extendprojmatrix3 { get; set; }
        public double? Extendprojmatrix4 { get; set; }
        public double? Extendprojmatrix5 { get; set; }
        public double? Extendprojmatrix6 { get; set; }
        public double? Extendprojmatrix7 { get; set; }
        public double? Extendprojmatrix8 { get; set; }
        public double? Extendprojmatrix9 { get; set; }
        public double? Extendprojmatrix10 { get; set; }
        public double? Extendprojmatrix11 { get; set; }
        public double? Extendprojmatrix12 { get; set; }
        public double? Extendprojmatrix13 { get; set; }
        public double? Extendprojmatrix14 { get; set; }
        public double? Extendprojmatrix15 { get; set; }
        public double? Extendprojmatrix16 { get; set; }
        public short? Verticaldatum { get; set; }
        public short? Undulationmodel { get; set; }
        public double? Averageundulation { get; set; }
        public string? Namedgeodeticdatum { get; set; }
    }
}
